export const UNAUTHORIZED = "PAE000";
export const INVALID_EMAIL_ERROR = "PAE001";
export const INVALID_PASSWORD_ERROR = "PAE002";
export const INVALID_CONFIRM_ERROR = "PAE003";
export const USER_ALREADY_EXISTED = "PAE004";
export const USER_NOT_FOUND = "PAE005";
export const LOGIN_WRONG_PASSWORD = "PAE006";

export const SAVE_DOCUMENT_INVALID_DOCUMENT_ID = "PAE007";
export const CREATE_DOCUMENT_INVALID_TITLE = "PAE008";
