export const SAVE_DOCUMENT_INVALID_DOCUMENT_ID = "PAE100";
export const CREATE_DOCUMENT_INVALID_TITLE = "PAE101";
export const SHARE_DOCUMENT_INVALID_PASSCODE = "PAE102";
export const DOCUMENT_NOT_FOUND = "PAE103";
export const DOCUMENT_ALREADY_SHARED = "PAE104";
export const DOCUMENT_CONTENT_REQUIRED = "PAE105";
export const DOCUMENT_VIEW_FORBIDDEN = "PAE106";
export const DOCUMENT_VIEW_FORBIDDEN_WRONG_PASSCODE = "PAE107";
export const DOCUMENT_UNSHARE_FORBIDDEN_WRONG_PASSCODE = "PAE108";
export const DOCUMENT_UPDATE_FAILED = "PAE109";
export const DOCUMENT_CREATE_FAILED = "PAE110";

export type DocumentErrorCode =
  | "PAE100"
  | "PAE101"
  | "PAE102"
  | "PAE103"
  | "PAE104"
  | "PAE105"
  | "PAE106"
  | "PAE107"
  | "PAE108"
  | "PAE109"
  | "PAE110";
